### ISSUE TITLE
A nested bundle doesn't have the right platforms listed in CFBundleSupportedPlatforms

### ISSUE THREAD

**Issue by cyril94440** [rhcad/vgios#41]
Hi,

I have this issue when trying to submit the app to the AppStore.
It comes from TouchVG.

"A nested bundle doesn't have the right platforms listed in CFBundleSupportedPlatforms"

Any clue ?

**Comment by cyril94440** [comment]
Seems that removing the key makes the trick, I'll let you know.

**Comment by rhcad** [comment]
Thanks you! Just delete the CFBundleSupportedPlatforms key in the info.plist.

There is a same answer in [stackoverflow](http://stackoverflow.com/questions/32733365/invalid-bundle-a-nested-bundle-doesnt-have-the-right-platforms-listed-in-cfbu) and [a blog of bloglovin.com](https://www.bloglovin.com/blogs/active-questions-tagged-objective-c-stack-8692345/how-to-add-custom-path-in-urlbyappendingpathcomponent-4570951650).

**Comment by cyril94440** [comment]
I got refused one more time. Let's try a clean + remove derived data, but I don't have any CFBundleSupportedPlatforms in any plist file
